# resolver: lts-5.15
# resolver: lts-6.27
# resolver: nightly-2017-01-31
resolver: lts-8.16

packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []

# arch: x86_64

# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
